package controller;

public enum ActionCommand {
	SHOW_WINDOW_DRAWING, SHOW_DIALOG_ADD_TRANSITION_FUNCION, SHOW_DIALOG_ADD_TRANSITION_TABLE,
	ADD_AUTOMATON_BY_FUNTIONS_TRANSITIONS, SHOW_EVALUATE_WORD, CHARGE_STATES, ADD_PANEL_NEW_FUNCION,
	REMOVE_FUNCION, IMPORT_AUTOMATON, EXPORT_AUTOMATON_IMG, EXPORT_AUTOMATON_XML, EXIT

}
